### ISSUE TITLE
Information about PELT implementation

### ISSUE THREAD

**Issue by Irfanwustl** [deepcharles/ruptures#176]
Hi, 
Thanks for the wonderful package. I am using PELT algorithm from the package. However, I am wondering what the effect of the jump parameter is. In the [documentation](https://centre-borelli.github.io/ruptures-docs/user-guide/detection/pelt/), there is a description. However, I am not sure I understand that 

Also, the authors of PELT have recently published a [multidimensional algorithm](https://link.springer.com/article/10.1007/s11222-020-09940-y). Have you implemented this for high-dimensional PELT? Or [this version](https://arxiv.org/pdf/1101.1438.pdf)?

Thanks again for the great package.

**Comment by deepcharles** [comment]
The jump parameter speeds up calculations. For instance, if `jump=3`, only the indexes 3, 6, 9,... are considered as potential change-points. If `jump=1`, all indexes are considered as potential change-points. Roughly, `jump=3` is three times faster than `jump=1`, since we compute three times less cost functions.

Thanks for the references, I will look into that and see if those methods can be integrated easily into `ruptures`.

**Comment by Irfanwustl** [comment]
Thanks.
