### ISSUE TITLE
pw_linear return extra dimension?

### ISSUE THREAD

**Issue by tylermanning** [deepcharles/ruptures#20]
Why is this the case? It's kind of unexpected and is counter to the other functions where the length of the signal and number of dimensions given returns a dataset that is the same size.

**Comment by deepcharles** [comment]
Hello,

The piecewise linear model is as follows:
![image](https://user-images.githubusercontent.com/14997422/75348168-9373af80-58a2-11ea-8a7f-27f72e859671.png)

The linear relationship is encoded by $a_t$, and for a piecewise linear model, the $a_t$ are piecewise constant.

The function `pw_linear` returns $y_t$ and $x_t$ in a single array (the first dimension is the $y_t$). That's why the returned array has an extra dimension.
