### ISSUE TITLE
High RAM consumption

### ISSUE THREAD

**Issue by hushchyn-mikhail** [deepcharles/ruptures#35]
Hi all,

Thanks a lot for this library. It is great! However, I found that it takes a lot of RAM for large samples. For en example, Window CPD method requires about 7 GB RAM for 1D time series with 20k samples and 9 change points. And I suppose, that this leads to non-linear dependency of time from n_samples.

**Comment by deepcharles** [comment]
Yes, that might happen for such long time series.

Which cost function (or model) are you using? I ask because over the summer I plan on implementing the most common costs in C, for better speed and memory management.

Also try tuning the "jump" argument when you instanciate Window. It results in less accurate detection but is faster.
