### ISSUE TITLE
Can CostAR handle multidimensional data?

### ISSUE THREAD

**Issue by daopingWu** [deepcharles/ruptures#36]
Hello, thanks a lot for your work. I have one question regarding using vector autoregressive cost to detect change points. I notice in the document the input signal is required to be 1-d for CostAR. However, when I use multidimensional signals, no error occurs and change points can still be detected.  Does this mean that CostAR works as a vector autoregressive cost when the input signal is multidimensional? If not, is there any way that I can use vector autoregressive cost in ruptures?

**Comment by deepcharles** [comment]
> However, when I use multidimensional signals, no error occurs and change points can still be detected.

Yes, I have noticed that, but that is really accidental, the method is not doing what you would expect. 

> is there any way that I can use vector autoregressive cost in ruptures?

At the moment, it is not implemented in `ruptures`. This is mostly because a naive implementation would be computationally intensive even for small time-series. 
However if you come across an article or code (in Python, R or C) that proposes a practical implementation, I would gladly add it.
